services:
  stockhub-postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stockhub
    ports:
      - "5432:5432"
    networks:
      - stockhub-net
    volumes:
      - stockhub-postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d/

  stockhub-redis:
    image: redis:8.2.2
    ports:
      - "6379:6379"
    networks:
      - stockhub-net
    volumes:
      - stockhub-redis-data:/data

  stockhub-zookeeper:
    image: confluentinc/cp-zookeeper:7.9.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - stockhub-net
    volumes:
      - stockhub-zookeeper-data:/var/lib/zookeeper/data
      - stockhub-zookeeper-log:/var/lib/zookeeper/log

  stockhub-kafka:
    image: confluentinc/cp-kafka:7.9.4
    depends_on:
      - stockhub-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: stockhub-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://stockhub-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - stockhub-net
    volumes:
      - stockhub-kafka-data:/var/lib/kafka/data

  stockhub-debezium-connect:
    image: debezium/connect:2.6
    depends_on:
      - stockhub-kafka
      - stockhub-postgres
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: stockhub-kafka:9092
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: stockhub_connect_configs
      OFFSET_STORAGE_TOPIC: stockhub_connect_offsets
      STATUS_STORAGE_TOPIC: stockhub_connect_status
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      PLUGIN_PATH: /kafka/connect,/kafka/connect-jdbc
    networks:
      - stockhub-net
    volumes:
      - ./plugins/jdbc:/kafka/connect-jdbc
      - stockhub-debezium-connect-data:/data

  stockhub-connector-configurator:
     image: curlimages/curl:latest
     depends_on:
       stockhub-debezium-connect:
         condition: service_started
     networks:
       - stockhub-net
     command: >
       /bin/sh -c "
        echo 'Waiting for Kafka Connect API to be ready on port 8083...';
        while [ $(curl -s -o /dev/null -w '%{http_code}' http://stockhub-debezium-connect:8083/connectors) -ne 200 ]; do
            echo 'Connect not ready yet... sleeping 5s';
            sleep 5;
        done;
        echo 'Kafka Connect API is ready! Registering connectors...';

        echo 'Registering Debezium Postgres Source Connector...';
        curl -X POST -H 'Content-Type: application/json' --data @/config/debezium-postgres-connector.json http://stockhub-debezium-connect:8083/connectors || true;

        echo 'Registering JDBC Sink Connector for Products...';
        curl -X POST -H 'Content-Type: application/json' --data @/config/sink-products-connector.json http://stockhub-debezium-connect:8083/connectors || true;

        echo 'Connector registration attempts complete.';
       "
     volumes:
       - ./config/debezium-postgres-connector.json:/config/debezium-postgres-connector.json
       - ./config/sink-products-connector.json:/config/sink-products-connector.json
     restart: "on-failure"

  stockhub-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - stockhub-kafka
      - stockhub-zookeeper
      - stockhub-debezium-connect
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: stockhub
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: stockhub-kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: stockhub-zookeeper:2181
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://stockhub-debezium-connect:8083
    networks:
      - stockhub-net

networks:
  stockhub-net:
    driver: bridge

volumes:
  stockhub-zookeeper-data:
  stockhub-zookeeper-log:
  stockhub-kafka-data:
  stockhub-postgres-data:
  stockhub-redis-data:
  stockhub-debezium-connect-data:
