// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stockhub.Modules.Orders.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Init3 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "symbol",
                schema: "orders",
                table: "trade");

            migrationBuilder.AddForeignKey(
                name: "FK_trade_mv_stock_stock_id",
                schema: "orders",
                table: "trade",
                column: "stock_id",
                principalSchema: "orders",
                principalTable: "mv_stock",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_trade_mv_stock_stock_id",
                schema: "orders",
                table: "trade");

            migrationBuilder.AddColumn<string>(
                name: "symbol",
                schema: "orders",
                table: "trade",
                type: "text",
                nullable: false,
                defaultValue: "");
        }
    }
}
