// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stockhub.Modules.Orders.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Init2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_order_stock_stock_id",
                schema: "orders",
                table: "order");

            migrationBuilder.DropForeignKey(
                name: "FK_order_user_user_id",
                schema: "orders",
                table: "order");

            migrationBuilder.DropForeignKey(
                name: "FK_portfolio_stock_stock_id",
                schema: "orders",
                table: "portfolio");

            migrationBuilder.DropForeignKey(
                name: "FK_portfolio_user_user_id",
                schema: "orders",
                table: "portfolio");

            migrationBuilder.DropPrimaryKey(
                name: "PK_user",
                schema: "orders",
                table: "user");

            migrationBuilder.DropPrimaryKey(
                name: "PK_stock",
                schema: "orders",
                table: "stock");

            migrationBuilder.DropColumn(
                name: "created_at",
                schema: "orders",
                table: "trade");

            migrationBuilder.DropColumn(
                name: "updated_at",
                schema: "orders",
                table: "trade");

            migrationBuilder.RenameTable(
                name: "user",
                schema: "orders",
                newName: "mv_user",
                newSchema: "orders");

            migrationBuilder.RenameTable(
                name: "stock",
                schema: "orders",
                newName: "mv_stock",
                newSchema: "orders");

            migrationBuilder.AddColumn<Guid>(
                name: "stock_id",
                schema: "orders",
                table: "trade",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddPrimaryKey(
                name: "PK_mv_user",
                schema: "orders",
                table: "mv_user",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_mv_stock",
                schema: "orders",
                table: "mv_stock",
                column: "id");

            migrationBuilder.CreateIndex(
                name: "IX_trade_buyer_id",
                schema: "orders",
                table: "trade",
                column: "buyer_id");

            migrationBuilder.CreateIndex(
                name: "IX_trade_seller_id",
                schema: "orders",
                table: "trade",
                column: "seller_id");

            migrationBuilder.CreateIndex(
                name: "IX_trade_stock_id",
                schema: "orders",
                table: "trade",
                column: "stock_id");

            migrationBuilder.AddForeignKey(
                name: "FK_order_mv_stock_stock_id",
                schema: "orders",
                table: "order",
                column: "stock_id",
                principalSchema: "orders",
                principalTable: "mv_stock",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_order_mv_user_user_id",
                schema: "orders",
                table: "order",
                column: "user_id",
                principalSchema: "orders",
                principalTable: "mv_user",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_portfolio_mv_stock_stock_id",
                schema: "orders",
                table: "portfolio",
                column: "stock_id",
                principalSchema: "orders",
                principalTable: "mv_stock",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_portfolio_mv_user_user_id",
                schema: "orders",
                table: "portfolio",
                column: "user_id",
                principalSchema: "orders",
                principalTable: "mv_user",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_order_mv_stock_stock_id",
                schema: "orders",
                table: "order");

            migrationBuilder.DropForeignKey(
                name: "FK_order_mv_user_user_id",
                schema: "orders",
                table: "order");

            migrationBuilder.DropForeignKey(
                name: "FK_portfolio_mv_stock_stock_id",
                schema: "orders",
                table: "portfolio");

            migrationBuilder.DropForeignKey(
                name: "FK_portfolio_mv_user_user_id",
                schema: "orders",
                table: "portfolio");

            migrationBuilder.DropIndex(
                name: "IX_trade_buyer_id",
                schema: "orders",
                table: "trade");

            migrationBuilder.DropIndex(
                name: "IX_trade_seller_id",
                schema: "orders",
                table: "trade");

            migrationBuilder.DropIndex(
                name: "IX_trade_stock_id",
                schema: "orders",
                table: "trade");

            migrationBuilder.DropPrimaryKey(
                name: "PK_mv_user",
                schema: "orders",
                table: "mv_user");

            migrationBuilder.DropPrimaryKey(
                name: "PK_mv_stock",
                schema: "orders",
                table: "mv_stock");

            migrationBuilder.DropColumn(
                name: "stock_id",
                schema: "orders",
                table: "trade");

            migrationBuilder.RenameTable(
                name: "mv_user",
                schema: "orders",
                newName: "user",
                newSchema: "orders");

            migrationBuilder.RenameTable(
                name: "mv_stock",
                schema: "orders",
                newName: "stock",
                newSchema: "orders");

            migrationBuilder.AddColumn<DateTime>(
                name: "created_at",
                schema: "orders",
                table: "trade",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<DateTime>(
                name: "updated_at",
                schema: "orders",
                table: "trade",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddPrimaryKey(
                name: "PK_user",
                schema: "orders",
                table: "user",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_stock",
                schema: "orders",
                table: "stock",
                column: "id");

            migrationBuilder.AddForeignKey(
                name: "FK_order_stock_stock_id",
                schema: "orders",
                table: "order",
                column: "stock_id",
                principalSchema: "orders",
                principalTable: "stock",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_order_user_user_id",
                schema: "orders",
                table: "order",
                column: "user_id",
                principalSchema: "orders",
                principalTable: "user",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_portfolio_stock_stock_id",
                schema: "orders",
                table: "portfolio",
                column: "stock_id",
                principalSchema: "orders",
                principalTable: "stock",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_portfolio_user_user_id",
                schema: "orders",
                table: "portfolio",
                column: "user_id",
                principalSchema: "orders",
                principalTable: "user",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
