// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stockhub.Modules.Users.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class UpdateTableName : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_users",
                schema: "users",
                table: "users");

            migrationBuilder.RenameTable(
                name: "users",
                schema: "users",
                newName: "user",
                newSchema: "users");

            migrationBuilder.AddPrimaryKey(
                name: "PK_user",
                schema: "users",
                table: "user",
                column: "id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_user",
                schema: "users",
                table: "user");

            migrationBuilder.RenameTable(
                name: "user",
                schema: "users",
                newName: "users",
                newSchema: "users");

            migrationBuilder.AddPrimaryKey(
                name: "PK_users",
                schema: "users",
                table: "users",
                column: "id");
        }
    }
}
